### ISSUE TITLE
Inheriting from ftlList

### ISSUE THREAD

**Issue by weixing1531** [SCM-NV/ftl#2]
subroutine NewCopyOther In the File"ftlList.F90_template" 
type(CAT(ftlList,FTL_TEMPLATE_TYPE_NAME)), intent(in)    :: other
shoud be chang to
class(CAT(ftlList,FTL_TEMPLATE_TYPE_NAME)), intent(in)    :: other
then the subclass of CAT( ) also use this method.

**Comment by pclausen** [comment]
Hi @weixing1531

Looks to be a bug in the ruby FUNIT stuff and I am working on a change to replace FUNIT and make files with cmake and ctest see https://github.com/exercism/fortran/pull/30

But I need to clean it up before change can be accepted.

So I hope this issue will be solved when my changes are done....

**Comment by robertrueger** [comment]
Hm, when I wrote this I didn't really have the use case of inheriting from the FTL containers in mind. On the contrary: I sometimes ran into random compiler issues with class() instead of type() in cases where it should have been totally equivalent, e.g. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79053 ...

What specific application do you have in mind for inheriting from ftlList? Isn't that problem better solved in another way, e.g. through composition, aka containing an ftlList in your class? Inheriting from the std containers is generally widely discouraged in the C++ world, and I think many of the arguments there also apply to the FTL containers.
